<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SampleTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>cc4cdb41-a354-4587-9109-274c00b762c8</testSuiteGuid>
   <testCaseLink>
      <guid>b1b903da-b4ce-4c89-b12a-d6eaa4eaa041</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HiringEmployeeTestCase</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>807832dd-dbee-4be6-9e93-65f07241005c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/HiringEmployeeTestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>807832dd-dbee-4be6-9e93-65f07241005c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HiringEmployeeFirstName</value>
         <variableId>422e05f5-77f5-40f4-8ddd-0db51ee4f923</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>807832dd-dbee-4be6-9e93-65f07241005c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HiringEmployeeLastName</value>
         <variableId>81fdb2cf-7b72-4a00-a630-ec78f69c4a68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1bd78eb-69f7-4f4a-baf3-a36ad0c03943</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f68ed1ab-ab0b-48fe-888b-792adfdafbad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HiredEmployeeVerification</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>99cbbb6a-2f02-4065-8202-297c5a4d87c2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/HiringEmployeeTestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af684dee-23b0-4eb5-8482-47db891f43fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>99cbbb6a-2f02-4065-8202-297c5a4d87c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HiringEmployeeFirstName</value>
         <variableId>01cc2c26-de77-4696-b3e3-2964979e6ec2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>99cbbb6a-2f02-4065-8202-297c5a4d87c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>HiringEmployeeLastName</value>
         <variableId>75c17f3c-54e5-4d08-bd6d-8db5e2662ef9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
