<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Personnel management</name>
   <tag></tag>
   <elementGuidId>6d21414b-3db3-4f33-95d7-988ac41a6ce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='defaultdashboard_1_HcmWorkforceWorkspace']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#defaultdashboard_1_HcmWorkforceWorkspace</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ccf725c6-24e4-4d7d-b006-41d8157ffcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-serverid</name>
      <type>Main</type>
      <value>116_0</value>
      <webElementGuid>536fe3e7-fedc-4de7-8869-6703ddf229bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-rootserverid</name>
      <type>Main</type>
      <value>3_0</value>
      <webElementGuid>fef10507-9dd1-4e4d-8ba7-07a479f22a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-controlname</name>
      <type>Main</type>
      <value>HcmWorkforceWorkspace</value>
      <webElementGuid>604d516f-64f7-4094-add7-16987ee968c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-role</name>
      <type>Main</type>
      <value>Tile</value>
      <webElementGuid>331e5d94-14df-4bf0-a181-e6c4b1e122c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Auto tile</value>
      <webElementGuid>444b25ac-e7d3-4b06-b15e-9dfe21bd1813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4877c595-8fd1-4583-ba78-f900e2e363aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c1bb56a-3384-42ec-b47c-23bc4d5935cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>visible: $data.Visible,
                    enabled: $data.Enabled,
                    click: $data.Clicked,
                    keyDown: $data.keyDown,
                    focusIn: $data.focusIn,
                    focusOut: $data.focusOut,
                    sizing: $dyn.layout.sizing($data),
                    skip: $dyn.ui.skip($data),
                    superTooltip: $dyn.ui.superTooltip($data),
                    attr: { 'data-dyn-button-display': $data.buttonDisplay,
                            'tile-type': $data.TileType,
                            'data-dyn-tile-size': $data.Size }</value>
      <webElementGuid>74f848e7-8626-47fa-a122-86f049a22430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-template-applied</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80394eda-7f95-475d-b2b5-792ac9b092db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>buttonstyle</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>efb5a2d8-c8f3-4f0c-acfc-24f132d95b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defaultdashboard_1_HcmWorkforceWorkspace</value>
      <webElementGuid>3ad8406f-8a09-484a-bdb1-484789381053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>defaultdashboard_1_HcmWorkforceWorkspace_text</value>
      <webElementGuid>166ac508-a409-40cd-b121-dc08d403b3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-lastvisible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8b55e6a-153f-4c10-b7b9-060cdabc8856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dyn-data-supertooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>da839f23-c3ba-4403-b727-ebf9d9320ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-button-display</name>
      <type>Main</type>
      <value>BackgroundImage</value>
      <webElementGuid>18037727-a0f0-49ff-9b07-b9178335a444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tile-type</name>
      <type>Main</type>
      <value>Standard</value>
      <webElementGuid>01442566-f7ec-4d6a-a744-40819aba2364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-tile-size</name>
      <type>Main</type>
      <value>Wide</value>
      <webElementGuid>6872975e-14ca-4c70-8017-a9b3c90b50f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>superToolTip</value>
      <webElementGuid>10f676a4-d13c-4a08-b61e-ba54b0701a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-superToolTip</value>
      <webElementGuid>29699dc8-46fd-4304-82ca-2598dc999c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personnel management</value>
      <webElementGuid>616416bb-f331-448b-a03b-a03bb279a689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defaultdashboard_1_HcmWorkforceWorkspace&quot;)</value>
      <webElementGuid>4e752451-dcff-436b-a15b-f12046bfc86a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='defaultdashboard_1_HcmWorkforceWorkspace']</value>
      <webElementGuid>87d649ac-e9e7-4288-b9f5-19be72a4d8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='defaultdashboard_1_Grp-45']/div[2]/div</value>
      <webElementGuid>6085a7df-1db4-4484-9698-35e84c39f554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People'])[1]/following::div[4]</value>
      <webElementGuid>f86ea29a-bf07-48cc-acf9-8fd5a59b3164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll management'])[1]/following::div[8]</value>
      <webElementGuid>86470231-0773-487d-b642-43761267b0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing and discount management'])[1]/preceding::div[2]</value>
      <webElementGuid>a9388680-bc65-484c-903b-7916554635ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[2]/div</value>
      <webElementGuid>2557ced0-49ee-4f72-964e-842b2d8b81e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'defaultdashboard_1_HcmWorkforceWorkspace' and (text() = 'Personnel management' or . = 'Personnel management')]</value>
      <webElementGuid>59c1df0e-081d-439e-a6d3-659bdf12d3a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
