<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HireEmployee_Hire</name>
   <tag></tag>
   <elementGuidId>cac6ac9e-8c9f-4c2d-aefb-11d2c05ed71f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='HcmWorkerNewWorker_4_OkNoRedirect_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HcmWorkerNewWorker_4_OkNoRedirect_label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd4b8591-92e4-46d0-b0b7-0151b1363cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-bind</name>
      <type>Main</type>
      <value>
            id: $data.Id + '_label', 
            ariaLabelFor: $dyn.ui.ariaLabelFor($data.Id, $data),
            css: { 'button-label' : !$dyn.value($data.IsLabelBubble),
                   'button-attach-label' : $dyn.value($data.IsLabelBubble) },
            attr: {
                'aria-describedby': $dyn.ui.getDescribedByData($data),
            }</value>
      <webElementGuid>790fc95e-ecaf-4126-acda-ac98a8d3394d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>HcmWorkerNewWorker_4_OkNoRedirect_label</value>
      <webElementGuid>18ba5c56-5725-40b0-be3c-180027a7d887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>HcmWorkerNewWorker_4_OkNoRedirect</value>
      <webElementGuid>4a4debeb-f721-4cfc-b89a-542e500f67c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-label</value>
      <webElementGuid>2f1fb880-37ee-4c19-b3c2-18e1af6f049c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>HcmWorkerNewWorker_4_OkNoRedirect_helptext</value>
      <webElementGuid>17336829-3eac-4d18-8a14-ceaafe682a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hire</value>
      <webElementGuid>fc043571-182a-47fd-b8b6-83a26113600e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HcmWorkerNewWorker_4_OkNoRedirect_label&quot;)</value>
      <webElementGuid>d85791b4-a546-43f2-b3a0-73c3d4620482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='HcmWorkerNewWorker_4_OkNoRedirect_label']</value>
      <webElementGuid>65b140d8-e514-4243-b27d-6a13b690f132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='HcmWorkerNewWorker_4_OkNoRedirect']/div/span[3]</value>
      <webElementGuid>8e789a8c-f2e7-46aa-8b9d-b41db4674b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Alt+Enter)'])[1]/following::span[1]</value>
      <webElementGuid>c0db0fca-851d-4c1a-8a4a-d4ee0bb76b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onboarding checklists'])[1]/following::span[4]</value>
      <webElementGuid>66ab4b53-005c-48d2-8cea-afd1fe50d6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hire and add details'])[1]/preceding::span[3]</value>
      <webElementGuid>f7965033-30d0-4e4f-b47a-4de7e97ccd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[6]</value>
      <webElementGuid>be7cdee1-4872-4e77-999f-e6a2a0d30236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hire']/parent::*</value>
      <webElementGuid>4ab64442-02bd-48d7-9de6-fb1f18a08b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div[2]/button/div/span[3]</value>
      <webElementGuid>d3e97acb-e682-48d0-ba9f-c1d5d4886e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'HcmWorkerNewWorker_4_OkNoRedirect_label' and (text() = 'Hire' or . = 'Hire')]</value>
      <webElementGuid>78a02e86-c9c1-47c4-8e33-8fcb92e3d18c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
