<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home-symbol</name>
   <tag></tag>
   <elementGuidId>eef35845-0277-4d71-974f-f152160951c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.workspace-image.Home-symbol</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bace8d9c-61f7-406c-83bf-65cfe5463507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>workspace-image Home-symbol</value>
      <webElementGuid>470aaead-380f-4b34-9fef-5a4fc0d26a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>89109027-3d71-4823-bac6-d54f1547912b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dyn-image-type</name>
      <type>Main</type>
      <value>Symbol</value>
      <webElementGuid>4fcb2b1e-37ad-4378-a1ce-30a0832da95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/span[@class=&quot;workspace-image Home-symbol&quot;]</value>
      <webElementGuid>6a4bdf8f-c256-463c-b25a-d9a67a9e6705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/span[2]</value>
      <webElementGuid>e4a6d6b3-4c4d-4932-a7f6-ae157a8b81f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span[2]</value>
      <webElementGuid>7c424acc-76a3-4634-9f73-43d80dd0880a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
