<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchResult SearchName field</name>
   <tag></tag>
   <elementGuidId>f65585b8-43da-4857-bc13-f07bbb32d903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NameAlias_List_207_0_0_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NameAlias_List_207_0_0_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fef8a864-d51f-451c-b2df-42591c6101ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NameAlias_List_207_0_0_input</value>
      <webElementGuid>5616d75e-7c8d-45c9-9dc5-9e5d2717ef0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>480003c7-650c-49ea-90bd-a62d4490c681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb41817e-8306-48fe-8f0f-9c4a47fd6650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2999f0ff-e2b9-45a5-8560-1d5eb57c6836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search name</value>
      <webElementGuid>b5ac82e1-662e-4556-8f53-a681d822d097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dyn-field _15m6b7a</value>
      <webElementGuid>ec0aad9c-3511-43da-858d-2ad7b21ace96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Test  Employee2</value>
      <webElementGuid>23ee0818-fb80-4173-b7b5-6a9f47cd1b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test  Employee2</value>
      <webElementGuid>2755ad59-e4e5-4279-80d3-fafca3dbf7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NameAlias_List_207_0_0_input&quot;)</value>
      <webElementGuid>a42aa76d-716e-4a0c-a31e-8bd1902fd55b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NameAlias_List_207_0_0_input']</value>
      <webElementGuid>c103d5d5-ec6d-42ef-aba9-929e2f6ed28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NameAlias_List_207_0_0']/div/input</value>
      <webElementGuid>33021607-5d4c-494a-8ebd-59b767e6d06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>b31bee04-c1aa-403e-8b21-1b1c9e8430b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NameAlias_List_207_0_0_input' and @type = 'text' and @title = 'Test  Employee2']</value>
      <webElementGuid>85352cee-0555-49fb-a61c-9b2cc836c458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
